# Generated by Django 4.0 on 2023-07-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='profiles.employer')),
            ],
        ),
    ]
