# Generated by Django 4.0 on 2023-07-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
    ]
